# Assignment 3

In [1]:
# Create a numpy array starting with step size of 3

In [51]:
import numpy as np

In [52]:
array1 = np.arange(2,50,3)

In [53]:
print(array1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [54]:
print(type(array1))

<class 'numpy.ndarray'>


In [55]:
# Problem 2
import numpy as np

In [56]:
# creating empty list1
list1 = list()
n1 = int(input('Enter the number of elements:'))
for i in range(0,n1):
    element = int(input())
    list1.append(element)
    
print(list1)

Enter the number of elements:5
25
56
78
95
133
[25, 56, 78, 95, 133]


In [57]:
# creating empty list 2

In [58]:
list2 = list()
n2 = int(input('Enter the number of elements'))
for i in range(0,n2):
    element = int(input())
    list2.append(element)
    
print(list2)


Enter the number of elements5
89
12
36
05
11
[89, 12, 36, 5, 11]


In [59]:
# coverting these lists into numpy arrays

array1 = np.array(list1)
array2 = np.array(list2)
print(array1)
print(array2)
print(type(array1))
print(type(array2))

[ 25  56  78  95 133]
[89 12 36  5 11]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Concatnating these two arrays

In [60]:
Array = np.concatenate((array1,array2))

In [61]:
print(Array)
print(type(Array))

[ 25  56  78  95 133  89  12  36   5  11]
<class 'numpy.ndarray'>


In [62]:
# Sorting Array
print(np.sort(Array))

[  5  11  12  25  36  56  78  89  95 133]


# Code Snippent of problem 3 to find size and dimension of ndarray

In [63]:
import numpy as np

In [64]:
a_1d = np.arange(3) # 1 d array
print(a_1d)

[0 1 2]


In [65]:
a_2d = np.arange(12).reshape(3,4)
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
a_3d = np.arange(24).reshape((2,3,4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [67]:
# Number of dimensions of numpy.ndarray: ndim

In [68]:
print(a_1d.ndim)
# 1

print(type(a_1d.ndim))
# <class 'int'>

print(a_2d.ndim)
# 2

print(a_3d.ndim)

1
<class 'int'>
2
3


In [22]:
# Size of numpy.ndArray(total number of elements):size

In [23]:
print(a_1d.size)
# 3

print(type(a_1d.size))
# <class 'int'>

print(a_2d.size)
# 12

print(a_3d.size)
# 24


3
<class 'int'>
12
24


# Converting a 1d array into 2d array

In [24]:
# reshaping a 1d array to 2d array

In [25]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # 1d Array
newarr = arr.reshape(3,4) # converting 1d array to 2d array using reshape()
print(newarr)
print(newarr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


# Stack two square numpy arrays vertically and horizontally

In [29]:
import numpy as np


In [32]:
Array_1 = np.array([[1,2],[3,4]])

In [33]:
print(Array_1)

[[1 2]
 [3 4]]


In [34]:
Array_2 = np.array([[5,6],[7,8]])
print(Array_2)

[[5 6]
 [7 8]]


In [35]:
# Stacking two arrays horizontally

In [36]:
out_Arr = np.hstack((Array_1,Array_2))
print(out_Arr)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
# Stacking two arrays vertically

In [38]:
out_arr = np.vstack((Array_1,Array_2))

In [39]:
print(out_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
# Finding unique items and counts of unique items

In [41]:
# Python’s numpy library provides a numpy.unique() function 
#to find the unique elements and it’s corresponding frequency in a numpy array.

In [42]:
import numpy as np

In [44]:
random_array = np.array([10,20,5,10,8,20,9])

In [45]:
# Get a tuple of unique values  
# and their frequency in 
# numpy array 

In [48]:
unique,frequency = np.unique(random_array,return_counts = True)

In [49]:
# print unique values array 
print("Unique Values:",  
      unique) 

Unique Values: [ 5  8  9 10 20]


In [50]:
# print frequency array 
print("Frequency Values:", 
      frequency)

Frequency Values: [1 1 1 2 2]


# Assignment 3 complete